/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -m -a cantataadaptor -i gui/mainwindow.h -l MainWindow /home/defaultuser/Downloads/tmp/cantata-2.4.1/dbus/mpd.cantata.xml
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef CANTATAADAPTOR_H
#define CANTATAADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "gui/mainwindow.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface mpd.cantata
 */
class CantataAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "mpd.cantata")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"mpd.cantata\">\n"
"    <method name=\"showError\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"error\"/>\n"
"    </method>\n"
"    <method name=\"dynamicStatus\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"error\"/>\n"
"    </method>\n"
"    <method name=\"load\">\n"
"      <arg direction=\"in\" type=\"as\" name=\"urls\"/>\n"
"    </method>\n"
"    <method name=\"setCollection\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"name\"/>\n"
"    </method>\n"
"    <property access=\"read\" type=\"as\" name=\"listActions\"/>\n"
"    <method name=\"triggerAction\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"name\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    CantataAdaptor(MainWindow *parent);
    virtual ~CantataAdaptor();

    inline MainWindow *parent() const
    { return static_cast<MainWindow *>(QObject::parent()); }

public: // PROPERTIES
    Q_PROPERTY(QStringList listActions READ listActions)
    QStringList listActions() const;

public Q_SLOTS: // METHODS
    void dynamicStatus(const QString &error);
    void load(const QStringList &urls);
    void setCollection(const QString &name);
    void showError(const QString &error);
    void triggerAction(const QString &name);
Q_SIGNALS: // SIGNALS
};

#endif
