/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -m -a cantataadaptor -i gui/mainwindow.h -l MainWindow /home/defaultuser/Downloads/tmp/cantata-2.4.1/dbus/mpd.cantata.xml
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "cantataadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class CantataAdaptor
 */

CantataAdaptor::CantataAdaptor(MainWindow *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

CantataAdaptor::~CantataAdaptor()
{
    // destructor
}

QStringList CantataAdaptor::listActions() const
{
    // get the value of property listActions
    return qvariant_cast< QStringList >(parent()->property("listActions"));
}

void CantataAdaptor::dynamicStatus(const QString &error)
{
    // handle method call mpd.cantata.dynamicStatus
    parent()->dynamicStatus(error);
}

void CantataAdaptor::load(const QStringList &urls)
{
    // handle method call mpd.cantata.load
    parent()->load(urls);
}

void CantataAdaptor::setCollection(const QString &name)
{
    // handle method call mpd.cantata.setCollection
    parent()->setCollection(name);
}

void CantataAdaptor::showError(const QString &error)
{
    // handle method call mpd.cantata.showError
    parent()->showError(error);
}

void CantataAdaptor::triggerAction(const QString &name)
{
    // handle method call mpd.cantata.triggerAction
    parent()->triggerAction(name);
}


#include "cantataadaptor.moc"
