/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -N -m -p settingsdaemoninterface /home/defaultuser/Downloads/tmp/cantata-2.4.1/dbus/org.gnome.SettingsDaemon.xml
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "settingsdaemoninterface.h"

/*
 * Implementation of interface class OrgGnomeSettingsDaemonInterface
 */

OrgGnomeSettingsDaemonInterface::OrgGnomeSettingsDaemonInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgGnomeSettingsDaemonInterface::~OrgGnomeSettingsDaemonInterface()
{
}


#include "settingsdaemoninterface.moc"
