/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -m -p upowerinterface /home/defaultuser/Downloads/tmp/cantata-2.4.1/dbus/org.freedesktop.UPower.xml
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef UPOWERINTERFACE_H
#define UPOWERINTERFACE_H

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface org.freedesktop.UPower
 */
class OrgFreedesktopUPowerInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.freedesktop.UPower"; }

public:
    OrgFreedesktopUPowerInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~OrgFreedesktopUPowerInterface();

    Q_PROPERTY(bool CanHibernate READ canHibernate)
    inline bool canHibernate() const
    { return qvariant_cast< bool >(property("CanHibernate")); }

    Q_PROPERTY(bool CanSuspend READ canSuspend)
    inline bool canSuspend() const
    { return qvariant_cast< bool >(property("CanSuspend")); }

    Q_PROPERTY(QString DaemonVersion READ daemonVersion)
    inline QString daemonVersion() const
    { return qvariant_cast< QString >(property("DaemonVersion")); }

    Q_PROPERTY(bool LidIsClosed READ lidIsClosed)
    inline bool lidIsClosed() const
    { return qvariant_cast< bool >(property("LidIsClosed")); }

    Q_PROPERTY(bool LidIsPresent READ lidIsPresent)
    inline bool lidIsPresent() const
    { return qvariant_cast< bool >(property("LidIsPresent")); }

    Q_PROPERTY(bool OnBattery READ onBattery)
    inline bool onBattery() const
    { return qvariant_cast< bool >(property("OnBattery")); }

    Q_PROPERTY(bool OnLowBattery READ onLowBattery)
    inline bool onLowBattery() const
    { return qvariant_cast< bool >(property("OnLowBattery")); }

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<> AboutToSleep()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("AboutToSleep"), argumentList);
    }

    inline QDBusPendingReply<QList<QDBusObjectPath> > EnumerateDevices()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("EnumerateDevices"), argumentList);
    }

    inline QDBusPendingReply<> Hibernate()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("Hibernate"), argumentList);
    }

    inline QDBusPendingReply<bool> HibernateAllowed()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("HibernateAllowed"), argumentList);
    }

    inline QDBusPendingReply<> Suspend()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("Suspend"), argumentList);
    }

    inline QDBusPendingReply<bool> SuspendAllowed()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("SuspendAllowed"), argumentList);
    }

Q_SIGNALS: // SIGNALS
    void Changed();
    void DeviceAdded(const QString &in0);
    void DeviceChanged(const QString &in0);
    void DeviceRemoved(const QString &in0);
    void Resuming();
    void Sleeping();
};

namespace org {
  namespace freedesktop {
    typedef ::OrgFreedesktopUPowerInterface UPower;
  }
}
#endif
